// <auto-generated />
using System;
using GolfClub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GolfClub.Migrations
{
    [DbContext(typeof(GolfClubContext))]
    [Migration("20230312213553_RemoveIDs")]
    partial class RemoveIDs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("GolfClub.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerFourMembershipNumberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerOneMembershipNumberId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerThreeMembershipNumberId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerTwoMembershipNumberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TeeTime")
                        .HasColumnType("TEXT");

                    b.HasKey("BookingId");

                    b.HasIndex("PlayerFourMembershipNumberId");

                    b.HasIndex("PlayerOneMembershipNumberId");

                    b.HasIndex("PlayerThreeMembershipNumberId");

                    b.HasIndex("PlayerTwoMembershipNumberId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("GolfClub.Models.Member", b =>
                {
                    b.Property<int>("MembershipNumberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Handicap")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("MembershipNumberId");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("GolfClub.Models.Booking", b =>
                {
                    b.HasOne("GolfClub.Models.Member", "PlayerFour")
                        .WithMany()
                        .HasForeignKey("PlayerFourMembershipNumberId");

                    b.HasOne("GolfClub.Models.Member", "PlayerOne")
                        .WithMany()
                        .HasForeignKey("PlayerOneMembershipNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfClub.Models.Member", "PlayerThree")
                        .WithMany()
                        .HasForeignKey("PlayerThreeMembershipNumberId");

                    b.HasOne("GolfClub.Models.Member", "PlayerTwo")
                        .WithMany()
                        .HasForeignKey("PlayerTwoMembershipNumberId");

                    b.Navigation("PlayerFour");

                    b.Navigation("PlayerOne");

                    b.Navigation("PlayerThree");

                    b.Navigation("PlayerTwo");
                });
#pragma warning restore 612, 618
        }
    }
}
